(() => {
'use strict';

const FALLBACK_CONFIG={
  season:2027,
  appName:'LGS 2027 Arena',
  examDate:'2027-06-13T09:30:00+03:00',
  nextSeason:{season:2028,appName:'LGS 2028 Arena',examDate:null},
  dailyQuestionTarget:50,
  questionSeconds:90,
  miniMockDistribution:{'Türkçe':20,'Matematik':20,'Fen Bilimleri':20,'İnkılap Tarihi':10,'Din Kültürü':10,'İngilizce':10},
  legalNotice:'Türkiye Yüzyılı Maarif Modeli esasları dikkate alınarak hazırlanmıştır. Bu uygulama Millî Eğitim Bakanlığının resmî uygulaması değildir ve MEB onayı iddiası taşımaz.'
};
const SUBJECTS=[
  {name:'Fen Bilimleri',short:'Fen',icon:'⚛',color:'#22c8dd'},
  {name:'Matematik',short:'Mat',icon:'π',color:'#397dff'},
  {name:'Türkçe',short:'Türkçe',icon:'▤',color:'#9a5cff'},
  {name:'İnkılap Tarihi',short:'İnkılap',icon:'▥',color:'#f0a23d'},
  {name:'Din Kültürü',short:'Din',icon:'◉',color:'#28bfc7'},
  {name:'İngilizce',short:'İngilizce',icon:'A',color:'#55c47a'}
];
const PROVINCES=['Adana','Adıyaman','Afyonkarahisar','Ağrı','Amasya','Ankara','Antalya','Artvin','Aydın','Balıkesir','Bilecik','Bingöl','Bitlis','Bolu','Burdur','Bursa','Çanakkale','Çankırı','Çorum','Denizli','Diyarbakır','Edirne','Elazığ','Erzincan','Erzurum','Eskişehir','Gaziantep','Giresun','Gümüşhane','Hakkâri','Hatay','Isparta','Mersin','İstanbul','İzmir','Kars','Kastamonu','Kayseri','Kırklareli','Kırşehir','Kocaeli','Konya','Kütahya','Malatya','Manisa','Kahramanmaraş','Mardin','Muğla','Muş','Nevşehir','Niğde','Ordu','Rize','Sakarya','Samsun','Siirt','Sinop','Sivas','Tekirdağ','Tokat','Trabzon','Tunceli','Şanlıurfa','Uşak','Van','Yozgat','Zonguldak','Aksaray','Bayburt','Karaman','Kırıkkale','Batman','Şırnak','Bartın','Ardahan','Iğdır','Yalova','Karabük','Kilis','Osmaniye','Düzce'];
const KEY='lgsArenaPwaV02';
const FREE_DAILY_LIMIT=50;
const REWARDED_AD_SECONDS=8;
const defaults={xp:0,streak:1,lastStudyDate:null,seenIds:[],rankedSolvedIds:[],history:[],daily:{date:'',count:0},noteRewards:{date:'',subjects:[]},province:'İstanbul',isPremium:false,studentName:'',timeoutTerminations:0,timeoutEvents:[],examHistory:[],adaptive:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], byId=id=>document.getElementById(id);
let CONFIG=FALLBACK_CONFIG,BANK=[],NOTES={},state={...defaults,...readState()};
let session=null,qIndex=0,answers=[],timer=null,remaining=90,reviewItems=[],reviewIndex=0,noteSubject='Fen Bilimleri',noteIndex=0,rewardedAdTimer=null;

function loadOptionalScript(src){return new Promise(resolve=>{if(document.querySelector(`script[data-arena-src="${src}"]`))return resolve();const s=document.createElement('script');s.src=src;s.dataset.arenaSrc=src;s.onload=()=>resolve();s.onerror=()=>resolve();document.head.appendChild(s)})}
function adaptive(){return window.LgsArenaAdaptive||null}
function readState(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
function saveRaw(){localStorage.setItem(KEY,JSON.stringify(state))}
function save(){saveRaw();renderAll()}
function today(){return new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Istanbul'})}
function normalizeDay(){const day=today();if(!state.daily||state.daily.date!==day)state.daily={date:day,count:0};if(!state.noteRewards||state.noteRewards.date!==day)state.noteRewards={date:day,subjects:[]};if(!Array.isArray(state.noteRewards.subjects))state.noteRewards.subjects=[];if(!Array.isArray(state.timeoutEvents))state.timeoutEvents=[];if(!Number.isFinite(state.timeoutTerminations))state.timeoutTerminations=0;if(!Array.isArray(state.examHistory))state.examHistory=[]}
function toast(msg){const e=byId('toast');if(!e)return;e.textContent=msg;e.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.add('hidden'),3000)}
function showPage(name){$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));$$('#bottomNav [data-nav]').forEach(b=>b.classList.toggle('selected',b.dataset.nav===name));byId('bottomNav')?.classList.toggle('hidden',['result','review','smartnotes','preference','membership'].includes(name));if(name==='subjects')renderSubjects();if(name==='progress')renderProgress();if(name==='smartnotes')renderSmartNotes()}
function examDate(){return new Date(CONFIG.examDate||FALLBACK_CONFIG.examDate)}
function countdown(){const diff=examDate()-new Date();if(diff<=0)return {ended:true,d:0,h:0,m:0,s:0};return {ended:false,d:Math.floor(diff/86400000),h:Math.floor(diff%86400000/3600000),m:Math.floor(diff%3600000/60000),s:Math.floor(diff%60000/1000)}}
function updateCountdown(){const x=countdown();if(byId('daysLeft'))byId('daysLeft').textContent=x.d;if(byId('clockLeft'))byId('clockLeft').textContent=x.ended?(CONFIG.nextSeason?.examDate?'Yeni dönem sayacı hazırlanıyor':'LGS 2028 dönemi · yeni sınav tarihi bekleniyor'):`${x.h} saat · ${x.m} dakika · ${x.s} saniye`;applySeasonBranding(x.ended)}
function applySeasonBranding(ended=false){const active=ended&&CONFIG.nextSeason?.appName?CONFIG.nextSeason.appName:CONFIG.appName;const year=ended&&CONFIG.nextSeason?.season?CONFIG.nextSeason.season:CONFIG.season;document.title=active;$$('.brand span').forEach(el=>el.textContent=`LGS ${year}`);const coverYear=$('.cover-branding span');if(coverYear)coverYear.textContent=`LGS ${year}`;const heroKicker=$('.arena-hero-kicker');if(heroKicker)heroKicker.textContent=`ZEUS İLE LGS ${year}`}
function subjectQuestions(name){return BANK.filter(q=>q.subject===name)}
function subjectHistory(name){return state.history.filter(h=>h.subject===name&&!h.assisted)}
function accuracy(name){const h=subjectHistory(name);return h.length?Math.round(h.filter(x=>x.correct).length/h.length*100):0}
function uniqueSeen(name){const ids=new Set(subjectQuestions(name).map(q=>q.id));return state.seenIds.filter(id=>ids.has(id)).length}
function rankData(){const solved=new Set(state.rankedSolvedIds).size,all=Math.max(1,state.history.filter(x=>!x.assisted&&x.selected!==null).length),correct=state.history.filter(x=>x.correct&&!x.assisted).length,acc=Math.round(correct/all*100);const total=250000,provinceTotals={'İstanbul':42000,'Ankara':19000,'İzmir':16500,'Bursa':12000,'Antalya':10000};const pt=provinceTotals[state.province]||3500;const score=solved*85+acc*11+state.xp*.12;return {solved,acc,total,pt,tr:Math.max(1,Math.round(total*Math.exp(-score/15000))),pr:Math.max(1,Math.round(pt*Math.exp(-score/12000)))}}
function renderAll(){normalizeDay();const target=CONFIG.dailyQuestionTarget||FREE_DAILY_LIMIT;if(byId('dailyProgress'))byId('dailyProgress').textContent=`${Math.min(state.daily.count,target)} / ${target}`;if(byId('streakValue'))byId('streakValue').textContent=`${state.streak} gün`;if(byId('levelValue'))byId('levelValue').textContent=1+Math.floor(state.xp/1000);if(byId('xpValue'))byId('xpValue').textContent=state.xp.toLocaleString('tr-TR');if(byId('xpBar'))byId('xpBar').style.width=`${state.xp%1000/10}%`;const r=rankData();if(byId('arenaTurkeyRank'))byId('arenaTurkeyRank').textContent=`${r.tr.toLocaleString('tr-TR')}.`;if(byId('arenaProvinceLabel'))byId('arenaProvinceLabel').textContent=state.province;if(byId('arenaProvinceRank'))byId('arenaProvinceRank').textContent=`${r.pr.toLocaleString('tr-TR')}.`;if(byId('arenaSolvedCount'))byId('arenaSolvedCount').textContent=r.solved;renderMiniSubjects();renderProgress();if(byId('planText'))byId('planText').textContent=state.isPremium?'Premium':'Ücretsiz';const totalBadge=$('section[data-page="subjects"] .page-title>b');if(totalBadge)totalBadge.textContent=BANK.length}
function renderMiniSubjects(){const box=byId('arenaSubjects');if(!box)return;box.innerHTML='';SUBJECTS.forEach(s=>{const total=Math.max(1,subjectQuestions(s.name).length),seen=uniqueSeen(s.name),pct=Math.round(seen/total*100);box.insertAdjacentHTML('beforeend',`<div class="mini-sub"><span style="color:${s.color}">${s.icon}</span><b>${s.short}</b><div><i style="width:${pct}%;background:${s.color}"></i></div><em>%${pct}</em></div>`)})}
function renderSubjects(){const box=byId('subjectCards');if(!box)return;box.innerHTML='';SUBJECTS.forEach(s=>{const total=subjectQuestions(s.name).length,seen=uniqueSeen(s.name),left=Math.max(0,total-seen),pct=total?seen/total*100:0;box.insertAdjacentHTML('beforeend',`<article class="subject-card" style="--c:${s.color}"><div class="subject-icon">${s.icon}</div><div><h3>${s.name}</h3><p>${seen}/${total} görüldü · ${left} yeni</p><div class="tiny-progress"><i style="width:${pct}%"></i></div></div><div class="subject-actions"><button data-notes="${s.name}">Akıllı Notlar</button><button data-start="${s.name}">10 Soru</button></div></article>`)});$$('[data-start]').forEach(b=>b.onclick=()=>startPractice(b.dataset.start));$$('[data-notes]').forEach(b=>b.onclick=()=>openNotes(b.dataset.notes))}
function renderProgress(){if(!byId('progressBars'))return;const bars=byId('progressBars');bars.innerHTML='';SUBJECTS.forEach(s=>{const a=accuracy(s.name);bars.insertAdjacentHTML('beforeend',`<div><span>${s.short}</span><i><b style="width:${a}%;background:${s.color}"></b></i><em>%${a}</em></div>`)});const all=state.history.filter(h=>!h.assisted&&h.selected!==null),ok=all.filter(h=>h.correct).length,pct=all.length?Math.round(ok/all.length*100):0;byId('overallPct').textContent=`${pct}%`;const r=rankData();byId('turkeyRank').textContent=`${r.tr.toLocaleString('tr-TR')}.`;byId('turkeyRankTotal').textContent=`/ ${r.total.toLocaleString('tr-TR')}`;byId('provinceRankLabel').textContent=state.province;byId('provinceRank').textContent=`${r.pr.toLocaleString('tr-TR')}.`;byId('provinceRankTotal').textContent=`/ ${r.pt.toLocaleString('tr-TR')}`;byId('rankSolvedCount').textContent=r.solved;byId('rankAccuracy').textContent=`${r.acc}%`;renderWeak()}
function renderWeak(){const map={};state.history.filter(h=>!h.assisted&&h.selected!==null).forEach(h=>{const k=h.topic;map[k]??={n:0,c:0};map[k].n++;if(h.correct)map[k].c++});const arr=Object.entries(map).map(([topic,v])=>({topic,pct:Math.round(v.c/v.n*100),n:v.n})).sort((a,b)=>a.pct-b.pct).slice(0,3);if(byId('weakTopics'))byId('weakTopics').innerHTML=arr.length?arr.map(x=>`<div><span>${x.topic}</span><b>%${x.pct}</b></div>`).join(''):'<p class="empty">Henüz yeterli çözüm yok.</p>'}
function setupProvince(){const s=byId('provinceSelect');if(!s)return;s.innerHTML=PROVINCES.map(p=>`<option ${p===state.province?'selected':''}>${p}</option>`).join('');s.onchange=()=>{state.province=s.value;save()}}
function unseen(name){const pool=subjectQuestions(name),seen=new Set(state.seenIds);return pool.filter(q=>!seen.has(q.id))}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function selectAdaptive(pool,count){const engine=adaptive();return engine?engine.pickQuestions(pool,count,state):shuffle(pool).slice(0,count)}
function openMembership(origin='premium'){window.dispatchEvent(new CustomEvent('lgsarena:open-membership',{detail:{origin}}))}
function showQuotaGate(){const overlay=byId('quotaOverlay');if(!overlay){openMembership('daily-limit');return}overlay.classList.remove('hidden');overlay.setAttribute('aria-hidden','false')}
function freeQuestionTake(){normalizeDay();if(state.isPremium)return 10;const remainingCount=Math.max(0,FREE_DAILY_LIMIT-Number(state.daily.count||0));if(remainingCount<=0){showQuotaGate();return 0}return Math.min(10,remainingCount)}
function startPractice(name){const take=freeQuestionTake();if(!take)return;const pool=unseen(name);if(pool.length<take){toast(`${name} havuzunda ${take} yeni soru kalmadı.`);return}startSession(selectAdaptive(pool,take),'practice',name)}
function startQuick(){const take=freeQuestionTake();if(!take)return;const fresh=BANK.filter(q=>!state.seenIds.includes(q.id));if(fresh.length<take){toast(`${take} yeni soru kalmadı.`);return}startSession(selectAdaptive(fresh,take),'practice','Karışık')}
function startMock(){if(!state.isPremium){openMembership('arena-exam');return}const qs=[];for(const s of SUBJECTS){const take=CONFIG.miniMockDistribution?.[s.name]||0;if(!take)continue;const p=unseen(s.name);if(p.length<take){toast(`${s.short} havuzunda ${take} yeni soru kalmadı.`);return}qs.push(...shuffle(p).slice(0,take))}startSession(shuffle(qs),'exam','LGS 2027 Arena')}
function openWrittenScenario(name){if(!state.isPremium){openMembership('written-scenario');return}toast(`${name} senaryosu Premium içerik paketinde hazırlanıyor.`)}
function startSession(qs,mode,title){session={questions:qs,mode,title,startedAt:Date.now(),endedByTimeout:false};qIndex=0;answers=[];showPage('solve');byId('solveLauncher').classList.add('hidden');byId('quizView').classList.remove('hidden');renderQuestion()}
function answer(){return answers[qIndex]??={selected:null,assisted:false,hint:false}}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function startTimer(){stopTimer();remaining=Number(CONFIG.questionSeconds)||90;tick();timer=setInterval(()=>{remaining--;tick();if(remaining<=0){stopTimer();endByTimeout()}},1000)}
function tick(){if(!byId('questionTimer'))return;byId('questionTimer').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;byId('questionTimer').classList.toggle('danger',remaining<=10)}
function endByTimeout(){if(!session)return;answer().selected=null;session.endedByTimeout=true;state.timeoutTerminations=(state.timeoutTerminations||0)+1;state.timeoutEvents=[...(state.timeoutEvents||[]),{at:new Date().toISOString(),mode:session.mode,title:session.title,questionIndex:qIndex+1,subject:session.questions[qIndex]?.subject||''}].slice(-100);saveRaw();finishSession('timeout')}
function renderQuestion(){const q=session.questions[qIndex],a=answer();if(!state.seenIds.includes(q.id)){state.seenIds.push(q.id);saveRaw()}byId('quizModeLabel').textContent=session.mode==='exam'?'DENEME':'ÇALIŞMA';byId('questionCounter').textContent=`${qIndex+1} / ${session.questions.length}`;byId('quizProgress').style.width=`${(qIndex+1)/session.questions.length*100}%`;byId('questionSubject').textContent=`${q.subject} · ${q.topic}`;byId('questionDifficulty').textContent=`${q.difficulty||'Orta'} · ${q.kind||'Kazanım'}`;byId('questionText').textContent=q.question;byId('helpBox').classList.add('hidden');const l=byId('optionList');l.innerHTML='';q.options.forEach((o,i)=>{const b=document.createElement('button');b.className='option-btn'+(a.selected===i?' selected':'');b.innerHTML=`<span>${String.fromCharCode(65+i)}</span><b>${o}</b>`;b.onclick=()=>{a.selected=i;$$('.option-btn').forEach((x,n)=>x.classList.toggle('selected',n===i))};l.appendChild(b)});byId('supportBar').classList.toggle('hidden',session.mode==='exam');startTimer()}
function help(type){const q=session.questions[qIndex],a=answer(),h=byId('helpBox');if(type==='hint'){a.hint=true;h.innerHTML=`<b>İpucu</b><p>${q.hint||'Sorudaki anahtar ifadeleri belirle.'}</p>`}else if(type==='zeus'){a.hint=true;h.innerHTML=`<b>Zeus</b><p>${q.hint||'Anahtar ifadeleri belirle.'} Seçenekleri tek tek ele.</p>`}else{a.assisted=true;a.selected=null;h.innerHTML=`<b>Çözüm Yolu</b><p>${q.solution||'Çözüm hazırlanıyor.'}</p><strong>Doğru cevap: ${String.fromCharCode(65+q.answer)}) ${q.options[q.answer]}</strong>`;$$('.option-btn').forEach(b=>b.disabled=true)}h.classList.remove('hidden')}
function nextQuestion(){stopTimer();if(qIndex<session.questions.length-1){qIndex++;renderQuestion()}else finishSession('completed')}
function updateStreak(){const d=today();if(state.lastStudyDate===d)return;if(state.lastStudyDate){const diff=Math.round((new Date(d)-new Date(state.lastStudyDate))/86400000);state.streak=diff===1?state.streak+1:1}else state.streak=1;state.lastStudyDate=d}
function finishSession(reason='completed'){if(!session)return;stopTimer();const count=reason==='timeout'?qIndex+1:session.questions.length,used=session.questions.slice(0,count);let c=0,w=0,b=0,a=0;const rows=used.map((q,i)=>{const x=answers[i]||{selected:null,assisted:false};let ok=false;if(x.assisted)a++;else if(x.selected===null)b++;else if(x.selected===q.answer){c++;ok=true}else w++;if(x.selected!==null&&!x.assisted&&!state.rankedSolvedIds.includes(q.id))state.rankedSolvedIds.push(q.id);return {id:q.id,subject:q.subject,topic:q.topic,difficulty:q.difficulty||'Orta',kind:q.kind||'Kazanım',selected:x.selected,answer:q.answer,correct:ok,assisted:x.assisted}});const xp=c*25;state.xp+=xp;state.daily.count+=rows.length;updateStreak();state.history.push(...rows);state.history=state.history.slice(-1200);let scoring={net:c-w/3,projectedTotalNet:null,estimatedScore:null,adaptive:state.adaptive};const engine=adaptive();if(engine){engine.ensureState(state);scoring=session.mode==='exam'?engine.recordExam(state,rows,{title:session.title,endedByTimeout:reason==='timeout'}):{...engine.summarizeRows(rows),projectedTotalNet:null,estimatedScore:null,adaptive:state.adaptive}}session.results={correct:c,wrong:w,blank:b,assisted:a,xp,total:rows.length,rows,endedByTimeout:reason==='timeout',net:scoring.net,projectedTotalNet:scoring.projectedTotalNet,estimatedScore:scoring.estimatedScore,adaptive:scoring.adaptive};saveRaw();if(state.isPremium)showResults();else if(session.mode==='exam')showResultUpsell();else if(rows.length>=10||state.daily.count>=FREE_DAILY_LIMIT)showRewardedAd('10 soru tamamlandı',()=>{if(state.daily.count>=FREE_DAILY_LIMIT)showQuotaGate();else showResults()});else showResults()}
function showResultUpsell(){const overlay=byId('resultUpsell');if(!overlay)return showResults();overlay.classList.remove('hidden')}
function showRewardedAd(context,onComplete){const ad=byId('adOverlay'),count=byId('adCount'),title=byId('adTitle'),message=byId('adMessage');if(!ad||!count){toast('Ödüllü reklam yüklenemedi. İnternet bağlantısını kontrol et.');return false}if(rewardedAdTimer)return false;if(title)title.textContent=context||'Ödüllü reklam';if(message)message.textContent='Reklam tamamlandığında bir sonraki aşama otomatik açılacak.';let n=REWARDED_AD_SECONDS;count.textContent=n;ad.classList.remove('hidden');ad.setAttribute('aria-hidden','false');document.body.classList.add('rewarded-ad-active');rewardedAdTimer=setInterval(()=>{n--;count.textContent=Math.max(0,n);if(n<=0){clearInterval(rewardedAdTimer);rewardedAdTimer=null;ad.classList.add('hidden');ad.setAttribute('aria-hidden','true');document.body.classList.remove('rewarded-ad-active');if(typeof onComplete==='function')onComplete()}},1000);return true}
function showResults(){const r=session.results;byId('resultCorrect').textContent=r.correct;byId('resultTotal').textContent=r.total;byId('rCorrect').textContent=r.correct;byId('rWrong').textContent=r.wrong;byId('rBlank').textContent=r.blank;byId('rAssisted').textContent=r.assisted;byId('rXp').textContent=`+${r.xp}`;byId('reviewWrong').classList.toggle('hidden',r.wrong===0);const kicker=$('.result-kicker');if(kicker)kicker.textContent=r.endedByTimeout?'SÜRE DOLDU · TEST SONLANDI':'ARENA TAMAMLANDI';showPage('result');renderAll();adaptive()?.decorateResultPage(r,session.mode);window.dispatchEvent(new CustomEvent('lgsarena:result',{detail:{mode:session.mode,estimatedScore:r.estimatedScore,projectedTotalNet:r.projectedTotalNet,province:state.province,endedByTimeout:r.endedByTimeout}}));if(r.endedByTimeout)toast('Süre dolduğu için test sonlandırıldı ve olay kaydedildi.')}
function openReview(){reviewItems=session.questions.map((q,i)=>({q,a:answers[i]})).filter(x=>x.a&&!x.a.assisted&&x.a.selected!==null&&x.a.selected!==x.q.answer);reviewIndex=0;if(!reviewItems.length)return;renderReview();showPage('review')}
function renderReview(){const {q,a}=reviewItems[reviewIndex];byId('reviewCounter').textContent=`${reviewIndex+1} / ${reviewItems.length}`;byId('reviewTopic').textContent=`${q.subject} · ${q.topic}`;byId('reviewQuestion').textContent=q.question;byId('reviewOptions').innerHTML=q.options.map((o,i)=>`<div class="review-option ${i===a.selected?'user-wrong':''} ${i===q.answer?'correct':''}">${String.fromCharCode(65+i)}) ${o}${i===a.selected?' · Senin cevabın':''}${i===q.answer?' · Doğru cevap':''}</div>`).join('');byId('reviewSolution').textContent=q.solution;byId('prevReview').disabled=reviewIndex===0;byId('nextReview').textContent=reviewIndex===reviewItems.length-1?'Bitti':'Sonraki'}
function openNotes(name){noteSubject=name;noteIndex=0;renderSmartNotes();showPage('smartnotes')}
function renderSmartNotes(){const list=NOTES[noteSubject]||[],n=list[noteIndex];byId('smartNotesSubjectTitle').textContent=noteSubject;byId('smartNotesCounter').textContent=list.length?`${noteIndex+1} / ${list.length}`:'0 / 0';byId('smartNoteSubjectTabs').innerHTML=SUBJECTS.map(s=>`<button data-note-subject="${s.name}" class="${s.name===noteSubject?'selected':''}" style="--c:${s.color}">${s.short}</button>`).join('');$$('[data-note-subject]').forEach(b=>b.onclick=()=>{noteSubject=b.dataset.noteSubject;noteIndex=0;renderSmartNotes()});if(!n){byId('smartNoteTopic').textContent='Hazırlanıyor';byId('smartNoteTitle').textContent='Bu ders için Akıllı Not hazırlanıyor';byId('smartNoteConcept').textContent='';byId('smartNoteAttention').textContent='';byId('smartNoteExample').textContent='';return}byId('smartNoteTopic').textContent=n.topic;byId('smartNoteTitle').textContent=n.title;byId('smartNoteConcept').textContent=n.concept;byId('smartNoteAttention').textContent=n.attention;byId('smartNoteExample').textContent=n.example;byId('prevSmartNote').disabled=noteIndex===0;byId('nextSmartNote').disabled=noteIndex===list.length-1}
function nextSmartNote(){const list=NOTES[noteSubject]||[];if(noteIndex>=list.length-1)return;const needsReward=!state.isPremium&&noteIndex===4&&!state.noteRewards.subjects.includes(noteSubject);if(!needsReward){noteIndex++;renderSmartNotes();return}showRewardedAd('5 Akıllı Not tamamlandı',()=>{if(!state.noteRewards.subjects.includes(noteSubject))state.noteRewards.subjects.push(noteSubject);saveRaw();noteIndex++;renderSmartNotes()})}
function zeusReply(text){const weak=SUBJECTS.map(s=>[s.name,accuracy(s.name)]).sort((a,b)=>a[1]-b[1])[0],route=state.adaptive?.route||'Dengeli Kazanım + Yeni Nesil',t=text.toLocaleLowerCase('tr-TR');let r=t.includes('plan')||t.includes('bugün')?`Bugün önce ${weak[0]} dersinden 10 soru çöz. Adaptif rotan: ${route}.`:t.includes('mat')?`Matematik doğruluğun %${accuracy('Matematik')}. Akıllı Notlar ile zayıf başlığı tekrar edip yeni sorulara geç.`:t.includes('fen')?`Fen doğruluğun %${accuracy('Fen Bilimleri')}. Kavramları neden-sonuç ilişkisiyle eşleştir.`:t.includes('ing')?`İngilizce doğruluğun %${accuracy('İngilizce')}. Ünite kelimelerini kısa tekrarlarla pekiştir.`:`Şu an öncelikli dersin ${weak[0]}. Adaptif rotan ${route}.`;const p=document.createElement('p');p.innerHTML=`<b>Zeus:</b> ${r}`;byId('zeusMessages').appendChild(p);byId('zeusMessages').scrollTop=9999}
function wire(){byId('skipCover').onclick=()=>{byId('cover').classList.remove('active');byId('cover').classList.add('hidden');byId('shell').classList.remove('hidden')};$$('[data-nav]').forEach(b=>b.onclick=()=>showPage(b.dataset.nav));byId('quickStart').onclick=startQuick;byId('startMock').onclick=startMock;const examCard=byId('examPremiumCard');examCard?.addEventListener('click',e=>{if(!e.target.closest('button'))startMock()});examCard?.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();startMock()}});$$('[data-written-scenario]').forEach(b=>b.onclick=()=>openWrittenScenario(b.dataset.writtenScenario));byId('quotaPremium').onclick=()=>{const gate=byId('quotaOverlay');gate.classList.add('hidden');gate.setAttribute('aria-hidden','true');openMembership('daily-limit')};byId('hintBtn').onclick=()=>help('hint');byId('solutionBtn').onclick=()=>help('solution');byId('askZeusBtn').onclick=()=>help('zeus');byId('nextBtn').onclick=nextQuestion;byId('quitQuiz').onclick=()=>{stopTimer();session=null;byId('solveLauncher').classList.remove('hidden');byId('quizView').classList.add('hidden');showPage('arena')};byId('resultHome').onclick=()=>{session=null;byId('solveLauncher').classList.remove('hidden');byId('quizView').classList.add('hidden');showPage('arena')};byId('reviewWrong').onclick=openReview;byId('closeReview').onclick=()=>showPage('result');byId('prevReview').onclick=()=>{if(reviewIndex>0){reviewIndex--;renderReview()}};byId('nextReview').onclick=()=>{if(reviewIndex<reviewItems.length-1){reviewIndex++;renderReview()}else showPage('result')};byId('smartNotesBack').onclick=()=>showPage('subjects');byId('prevSmartNote').onclick=()=>{if(noteIndex>0){noteIndex--;renderSmartNotes()}};byId('nextSmartNote').onclick=nextSmartNote;byId('smartNotePractice').onclick=()=>startPractice(noteSubject);byId('togglePlan').onclick=()=>openMembership('progress');byId('resultUpsellYes').onclick=()=>{byId('resultUpsell').classList.add('hidden');openMembership('result')};byId('resultUpsellNo').onclick=()=>{byId('resultUpsell').classList.add('hidden');showResults()};window.addEventListener('lgsarena:premium-set',event=>{state.isPremium=!!event.detail?.isPremium;save();window.dispatchEvent(new CustomEvent('lgsarena:premium-changed',{detail:{isPremium:state.isPremium}}))});window.addEventListener('lgsarena:continue-free-result',()=>{if(session?.results)showResults()});byId('zeusSend').onclick=()=>{const i=byId('zeusInput'),v=i.value.trim();if(!v)return;const p=document.createElement('p');p.textContent=`Sen: ${v}`;byId('zeusMessages').appendChild(p);i.value='';zeusReply(v)};byId('zeusInput').onkeydown=e=>{if(e.key==='Enter')byId('zeusSend').click()};$$('[data-zeus-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.zeusAction;if(a==='test')startQuick();else if(a==='plan')zeusReply('bugün plan');else if(a==='weak')zeusReply('zayıf');else byId('zeusInput').focus()});byId('bellBtn').onclick=()=>toast('Bildirim merkezi sonraki sürümde bağlanacak.')}
function renderLaunchers(){const box=byId('solveSubjects');box.innerHTML=SUBJECTS.map(s=>`<button data-launch="${s.name}" style="--c:${s.color}"><b>${s.icon}</b><span>${s.short}</span><small>10 yeni soru</small></button>`).join('');$$('[data-launch]').forEach(b=>b.onclick=()=>startPractice(b.dataset.launch))}
function patchStaticCopy(){const cover=$('#cover img');if(cover&&CONFIG.coverAsset)cover.src=CONFIG.coverAsset;const ring=$('section[data-page="mock"] .mock-ring span');if(ring)ring.textContent='90';const label=$('section[data-page="mock"] .mock-card>div>span');if(label)label.textContent='DENEME';const title=$('section[data-page="mock"] .mock-card h2');if(title)title.textContent='LGS 2027 Arena';const mockText=$('section[data-page="mock"] .mock-card p');if(mockText)mockText.textContent='6 ders · 90 soru · LGS soru dağılımı · sonuç sonunda açıklanır';const start=byId('startMock');if(start)start.textContent='DENEMEYE BAŞLA · PREMIUM';const notice=$('.cover .model-notice');if(notice)notice.textContent=CONFIG.legalNotice||FALLBACK_CONFIG.legalNotice}
async function init(){normalizeDay();await Promise.all([loadOptionalScript('./config.js'),loadOptionalScript('./data/ingilizce.js'),loadOptionalScript('./adaptive-v42.js')]);CONFIG=window.LGS_ARENA_CONFIG||FALLBACK_CONFIG;BANK=window.QUESTION_BANK||[];NOTES=window.SMART_NOTES||{};BANK.forEach(q=>{if(!q.kind)q.kind=['Zor','Efsane'].includes(q.difficulty)?'Yeni Nesil':'Kazanım'});adaptive()?.ensureState(state);saveRaw();setupProvince();renderLaunchers();renderSubjects();wire();patchStaticCopy();renderAll();updateCountdown();setInterval(updateCountdown,1000);showPage('arena')}
init();
})();









