(function(){
'use strict';
var KEY='lgsArenaPwaV02';
var SUBJECTS=[
 {name:'Fen Bilimleri',short:'Fen',icon:'⚛',color:'#22c8dd'},
 {name:'Matematik',short:'Mat',icon:'π',color:'#397dff'},
 {name:'Türkçe',short:'Türkçe',icon:'▤',color:'#9a5cff'},
 {name:'İnkılap Tarihi',short:'İnkılap',icon:'▥',color:'#f0a23d'},
 {name:'Din Kültürü',short:'Din',icon:'◉',color:'#28bfc7'},
 {name:'Yabancı Dil',short:'İngilizce',icon:'EN',color:'#49b982'}
];
var PROVINCES=['Adana','Adıyaman','Afyonkarahisar','Ağrı','Amasya','Ankara','Antalya','Artvin','Aydın','Balıkesir','Bilecik','Bingöl','Bitlis','Bolu','Burdur','Bursa','Çanakkale','Çankırı','Çorum','Denizli','Diyarbakır','Edirne','Elazığ','Erzincan','Erzurum','Eskişehir','Gaziantep','Giresun','Gümüşhane','Hakkâri','Hatay','Isparta','Mersin','İstanbul','İzmir','Kars','Kastamonu','Kayseri','Kırklareli','Kırşehir','Kocaeli','Konya','Kütahya','Malatya','Manisa','Kahramanmaraş','Mardin','Muğla','Muş','Nevşehir','Niğde','Ordu','Rize','Sakarya','Samsun','Siirt','Sinop','Sivas','Tekirdağ','Tokat','Trabzon','Tunceli','Şanlıurfa','Uşak','Van','Yozgat','Zonguldak','Aksaray','Bayburt','Karaman','Kırıkkale','Batman','Şırnak','Bartın','Ardahan','Iğdır','Yalova','Karabük','Kilis','Osmaniye','Düzce'];
var defaults={xp:0,streak:1,lastStudyDate:null,seenIds:[],rankedSolvedIds:[],history:[],daily:{date:'',count:0},province:'İstanbul',isPremium:false,timeoutEnds:0};
var state=loadState();
var session=null,qIndex=0,answers=[],timer=null,remaining=90,reviewItems=[],reviewIndex=0,noteSubject='Fen Bilimleri',noteIndex=0;

function id(x){return document.getElementById(x)}
function all(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function bank(){return Array.isArray(window.QUESTION_BANK)?window.QUESTION_BANK:[]}
function notes(){return window.SMART_NOTES||{}}
function loadState(){
 var raw={};try{raw=JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch(e){}
 var s={};Object.keys(defaults).forEach(function(k){s[k]=raw[k]!==undefined?raw[k]:defaults[k]});
 if(!Array.isArray(s.seenIds))s.seenIds=[];if(!Array.isArray(s.rankedSolvedIds))s.rankedSolvedIds=[];if(!Array.isArray(s.history))s.history=[];
 if(!s.daily||typeof s.daily!=='object')s.daily={date:'',count:0};
 if(typeof s.daily.count!=='number')s.daily.count=0;if(!s.daily.date)s.daily.date='';
 return s;
}
function persist(render){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}if(render!==false)renderAll()}
function today(){return new Date().toISOString().slice(0,10)}
function normalizeDay(){if(state.daily.date!==today())state.daily={date:today(),count:0}}
function toast(msg){var e=id('toast');if(!e)return;e.textContent=msg;e.classList.remove('hidden');clearTimeout(window.__coreToast);window.__coreToast=setTimeout(function(){e.classList.add('hidden')},3000)}
function fatal(msg){var e=id('toast');if(e){e.textContent='Uygulama hatası: '+msg;e.classList.remove('hidden');e.style.background='#7b1621';e.style.zIndex='9999'}console.error(msg)}
window.addEventListener('error',function(e){fatal((e&&e.message)||'Bilinmeyen JavaScript hatası')});
window.addEventListener('unhandledrejection',function(e){fatal('Modül yükleme hatası')});

function showPage(name){
 all('.page').forEach(function(p){p.classList.toggle('active',p.getAttribute('data-page')===name)});
 all('#bottomNav [data-nav]').forEach(function(b){b.classList.toggle('selected',b.getAttribute('data-nav')===name)});
 var nav=id('bottomNav');if(nav)nav.classList.toggle('hidden',name==='result'||name==='review'||name==='smartnotes');
 if(name==='subjects')renderSubjects();if(name==='progress')renderProgress();if(name==='smartnotes')renderSmartNotes();
}
function subjectQuestions(name){return bank().filter(function(q){return q.subject===name})}
function subjectHistory(name){return state.history.filter(function(h){return h.subject===name&&!h.assisted})}
function accuracy(name){var h=subjectHistory(name).filter(function(x){return x.selected!==null});if(!h.length)return 0;return Math.round(h.filter(function(x){return x.correct}).length/h.length*100)}
function uniqueSeen(name){var ids={};subjectQuestions(name).forEach(function(q){ids[q.id]=1});return state.seenIds.filter(function(x){return ids[x]}).length}
function rankData(){
 var solved={};state.rankedSolvedIds.forEach(function(x){solved[x]=1});var solvedCount=Object.keys(solved).length;
 var usable=state.history.filter(function(x){return !x.assisted&&x.selected!==null});var correct=usable.filter(function(x){return x.correct}).length;var acc=usable.length?Math.round(correct/usable.length*100):0;
 var total=250000,pt=state.province==='İstanbul'?42000:state.province==='Ankara'?19000:state.province==='İzmir'?16500:state.province==='Bursa'?12000:state.province==='Antalya'?10000:3500;
 var score=solvedCount*85+acc*11+Number(state.xp||0)*.12;return {solved:solvedCount,acc:acc,total:total,pt:pt,tr:Math.max(1,Math.round(total*Math.exp(-score/15000))),pr:Math.max(1,Math.round(pt*Math.exp(-score/12000)))};
}
function renderMiniSubjects(){var box=id('arenaSubjects');if(!box)return;box.innerHTML='';SUBJECTS.forEach(function(s){var total=Math.max(1,subjectQuestions(s.name).length),seen=uniqueSeen(s.name),pct=Math.round(seen/total*100);box.insertAdjacentHTML('beforeend','<div class="mini-sub"><span style="color:'+s.color+'">'+s.icon+'</span><b>'+s.short+'</b><div><i style="width:'+pct+'%;background:'+s.color+'"></i></div><em>%'+pct+'</em></div>')})}
function renderSubjects(){var box=id('subjectCards');if(!box)return;box.innerHTML='';SUBJECTS.forEach(function(s){var total=subjectQuestions(s.name).length,seen=uniqueSeen(s.name),left=Math.max(0,total-seen),pct=total?seen/total*100:0;box.insertAdjacentHTML('beforeend','<article class="subject-card" style="--c:'+s.color+'"><div class="subject-icon">'+s.icon+'</div><div><h3>'+s.name+'</h3><p>'+seen+'/'+total+' görüldü · '+left+' yeni</p><div class="tiny-progress"><i style="width:'+pct+'%"></i></div></div><div class="subject-actions"><button data-notes="'+s.name+'">Akıllı Notlar</button><button data-start="'+s.name+'">10 Soru</button></div></article>')});
 all('[data-start]').forEach(function(b){b.onclick=function(){startPractice(b.getAttribute('data-start'))}});all('[data-notes]').forEach(function(b){b.onclick=function(){openNotes(b.getAttribute('data-notes'))}})
}
function renderLaunchers(){var box=id('solveSubjects');if(!box)return;box.innerHTML=SUBJECTS.map(function(s){return '<button data-launch="'+s.name+'" style="--c:'+s.color+'"><b>'+s.icon+'</b><span>'+s.short+'</span><small>10 yeni soru</small></button>'}).join('');all('[data-launch]').forEach(function(b){b.onclick=function(){startPractice(b.getAttribute('data-launch'))}})}
function renderWeak(){var map={};state.history.filter(function(h){return !h.assisted&&h.selected!==null}).forEach(function(h){var k=h.topic||'Konu';if(!map[k])map[k]={n:0,c:0};map[k].n++;if(h.correct)map[k].c++});var arr=Object.keys(map).map(function(k){return {topic:k,pct:Math.round(map[k].c/map[k].n*100),n:map[k].n}}).sort(function(a,b){return a.pct-b.pct}).slice(0,3);var box=id('weakTopics');if(box)box.innerHTML=arr.length?arr.map(function(x){return '<div><span>'+x.topic+'</span><b>%'+x.pct+'</b></div>'}).join(''):'<p class="empty">Henüz yeterli çözüm yok.</p>'}
function renderProgress(){var bars=id('progressBars');if(!bars)return;bars.innerHTML='';SUBJECTS.forEach(function(s){var a=accuracy(s.name);bars.insertAdjacentHTML('beforeend','<div><span>'+s.short+'</span><i><b style="width:'+a+'%;background:'+s.color+'"></b></i><em>%'+a+'</em></div>')});var usable=state.history.filter(function(h){return !h.assisted&&h.selected!==null}),ok=usable.filter(function(h){return h.correct}).length,pct=usable.length?Math.round(ok/usable.length*100):0;if(id('overallPct'))id('overallPct').textContent=pct+'%';var r=rankData();if(id('turkeyRank'))id('turkeyRank').textContent=r.tr.toLocaleString('tr-TR')+'.';if(id('turkeyRankTotal'))id('turkeyRankTotal').textContent='/ '+r.total.toLocaleString('tr-TR');if(id('provinceRankLabel'))id('provinceRankLabel').textContent=state.province;if(id('provinceRank'))id('provinceRank').textContent=r.pr.toLocaleString('tr-TR')+'.';if(id('provinceRankTotal'))id('provinceRankTotal').textContent='/ '+r.pt.toLocaleString('tr-TR');if(id('rankSolvedCount'))id('rankSolvedCount').textContent=r.solved;if(id('rankAccuracy'))id('rankAccuracy').textContent=r.acc+'%';renderWeak()}
function renderAll(){normalizeDay();if(id('dailyProgress'))id('dailyProgress').textContent=Math.min(state.daily.count,25)+' / 25';if(id('streakValue'))id('streakValue').textContent=state.streak+' gün';if(id('levelValue'))id('levelValue').textContent=1+Math.floor(Number(state.xp||0)/1000);if(id('xpValue'))id('xpValue').textContent=Number(state.xp||0).toLocaleString('tr-TR');if(id('xpBar'))id('xpBar').style.width=(Number(state.xp||0)%1000/10)+'%';var r=rankData();if(id('arenaTurkeyRank'))id('arenaTurkeyRank').textContent=r.tr.toLocaleString('tr-TR')+'.';if(id('arenaProvinceLabel'))id('arenaProvinceLabel').textContent=state.province;if(id('arenaProvinceRank'))id('arenaProvinceRank').textContent=r.pr.toLocaleString('tr-TR')+'.';if(id('arenaSolvedCount'))id('arenaSolvedCount').textContent=r.solved;if(id('planText'))id('planText').textContent=state.isPremium?'Reklamsız':'Ücretsiz';renderMiniSubjects();renderProgress()}
function setupProvince(){var s=id('provinceSelect');if(!s)return;s.innerHTML=PROVINCES.map(function(p){return '<option'+(p===state.province?' selected':'')+'>'+p+'</option>'}).join('');s.onchange=function(){state.province=s.value;persist()}}
function shuffle(a){var x=a.slice();for(var i=x.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=x[i];x[i]=x[j];x[j]=t}return x}
function unseen(name){var seen={};state.seenIds.forEach(function(x){seen[x]=1});return subjectQuestions(name).filter(function(q){return !seen[q.id]})}
function startPractice(name){var p=unseen(name);if(p.length<10)p=subjectQuestions(name);if(p.length<1){toast(name+' soru havuzu yüklenemedi.');return}startSession(shuffle(p).slice(0,Math.min(10,p.length)),'practice',name)}
function startQuick(){var p=bank().filter(function(q){return state.seenIds.indexOf(q.id)<0});if(p.length<10)p=bank();if(!p.length){toast('Soru havuzu henüz yüklenmedi.');return}startSession(shuffle(p).slice(0,Math.min(10,p.length)),'practice','Karışık')}
function startSession(qs,mode,title){session={questions:qs,mode:mode,title:title,startedAt:new Date().toISOString()};qIndex=0;answers=[];showPage('solve');if(id('solveLauncher'))id('solveLauncher').classList.add('hidden');if(id('quizView'))id('quizView').classList.remove('hidden');renderQuestion()}
function currentAnswer(){if(!answers[qIndex])answers[qIndex]={selected:null,assisted:false,hint:false};return answers[qIndex]}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function tick(){var el=id('questionTimer');if(el){el.textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');el.classList.toggle('danger',remaining<=10)}}
function startTimer(){stopTimer();remaining=90;tick();timer=setInterval(function(){remaining--;tick();if(remaining<=0){stopTimer();if(currentAnswer().selected===null){state.timeoutEnds=Number(state.timeoutEnds||0)+1;persist(false);finishSession('question-timeout')}else nextQuestion()}},1000)}
function renderQuestion(){if(!session||!session.questions.length)return;var q=session.questions[qIndex],a=currentAnswer();if(state.seenIds.indexOf(q.id)<0){state.seenIds.push(q.id);persist(false)}if(id('quizModeLabel'))id('quizModeLabel').textContent=session.mode==='exam'?'DENEME':'ÇALIŞMA';if(id('questionCounter'))id('questionCounter').textContent=(qIndex+1)+' / '+session.questions.length;if(id('quizProgress'))id('quizProgress').style.width=((qIndex+1)/session.questions.length*100)+'%';if(id('questionSubject'))id('questionSubject').textContent=(q.subject||'')+' · '+(q.topic||'');if(id('questionDifficulty'))id('questionDifficulty').textContent=(q.questionType?String(q.questionType).toUpperCase()+' · ':'')+(q.difficulty||'Orta');if(id('questionText'))id('questionText').textContent=q.question||'';if(id('helpBox'))id('helpBox').classList.add('hidden');var list=id('optionList');if(list){list.innerHTML='';(q.options||[]).forEach(function(o,i){var b=document.createElement('button');b.className='option-btn'+(a.selected===i?' selected':'');b.innerHTML='<span>'+String.fromCharCode(65+i)+'</span><b>'+o+'</b>';b.onclick=function(){a.selected=i;all('.option-btn').forEach(function(x,n){x.classList.toggle('selected',n===i)})};list.appendChild(b)})}if(id('supportBar'))id('supportBar').classList.toggle('hidden',session.mode==='exam');startTimer()}
function help(type){if(!session)return;var q=session.questions[qIndex],a=currentAnswer(),h=id('helpBox');if(!h)return;if(type==='hint'){a.hint=true;h.innerHTML='<b>İpucu</b><p>'+(q.hint||'Sorudaki anahtar ifadeleri belirle.')+'</p>'}else if(type==='zeus'){a.hint=true;h.innerHTML='<b>Zeus</b><p>'+(q.hint||'Anahtar ifadeleri belirleyip seçenekleri ele.')+'</p>'}else{a.assisted=true;a.selected=null;h.innerHTML='<b>Çözüm Yolu</b><p>'+(q.solution||'Çözüm açıklaması hazırlanıyor.')+'</p><strong>Doğru cevap: '+String.fromCharCode(65+Number(q.answer||0))+') '+((q.options||[])[Number(q.answer||0)]||'')+'</strong>';all('.option-btn').forEach(function(b){b.disabled=true})}h.classList.remove('hidden')}
function nextQuestion(){stopTimer();if(!session)return;if(qIndex<session.questions.length-1){qIndex++;renderQuestion()}else finishSession('completed')}
function updateStreak(){var d=today();if(state.lastStudyDate===d)return;if(state.lastStudyDate){var diff=Math.round((new Date(d)-new Date(state.lastStudyDate))/86400000);state.streak=diff===1?Number(state.streak||1)+1:1}else state.streak=1;state.lastStudyDate=d}
function finishSession(reason){stopTimer();if(!session)return;var c=0,w=0,b=0,a=0,now=new Date().toISOString();var rows=session.questions.map(function(q,i){var x=answers[i]||{selected:null,assisted:false};var ok=false;if(x.assisted)a++;else if(x.selected===null)b++;else if(Number(x.selected)===Number(q.answer)){c++;ok=true}else w++;if(x.selected!==null&&!x.assisted&&state.rankedSolvedIds.indexOf(q.id)<0)state.rankedSolvedIds.push(q.id);return {id:q.id,subject:q.subject,topic:q.topic,selected:x.selected,answer:q.answer,correct:ok,assisted:!!x.assisted,difficulty:q.difficulty||'Orta',questionType:q.questionType||q.type||'Kazanım',completedAt:now}});var xp=c*25;state.xp=Number(state.xp||0)+xp;state.daily.count=Number(state.daily.count||0)+rows.length;updateStreak();state.history=state.history.concat(rows).slice(-1200);session.results={correct:c,wrong:w,blank:b,assisted:a,xp:xp,total:rows.length,rows:rows,reason:reason};persist(false);showResults();try{window.dispatchEvent(new CustomEvent('lgsarena:session-finished',{detail:{session:session,results:session.results}}))}catch(e){}if(reason==='question-timeout')toast('Süre doldu ve cevap işaretlenmediği için test sona erdi.')}
function showResults(){var r=session&&session.results;if(!r)return;if(id('resultCorrect'))id('resultCorrect').textContent=r.correct;if(id('resultTotal'))id('resultTotal').textContent=r.total;if(id('rCorrect'))id('rCorrect').textContent=r.correct;if(id('rWrong'))id('rWrong').textContent=r.wrong;if(id('rBlank'))id('rBlank').textContent=r.blank;if(id('rAssisted'))id('rAssisted').textContent=r.assisted;if(id('rXp'))id('rXp').textContent='+'+r.xp;if(id('reviewWrong'))id('reviewWrong').classList.toggle('hidden',r.wrong===0);showPage('result');renderAll()}
function openReview(){if(!session)return;reviewItems=session.questions.map(function(q,i){return {q:q,a:answers[i]}}).filter(function(x){return x.a&&!x.a.assisted&&x.a.selected!==null&&Number(x.a.selected)!==Number(x.q.answer)});reviewIndex=0;if(!reviewItems.length){toast('İncelenecek yanlış yok.');return}renderReview();showPage('review')}
function renderReview(){var item=reviewItems[reviewIndex];if(!item)return;var q=item.q,a=item.a;if(id('reviewCounter'))id('reviewCounter').textContent=(reviewIndex+1)+' / '+reviewItems.length;if(id('reviewTopic'))id('reviewTopic').textContent=(q.subject||'')+' · '+(q.topic||'');if(id('reviewQuestion'))id('reviewQuestion').textContent=q.question||'';if(id('reviewOptions'))id('reviewOptions').innerHTML=(q.options||[]).map(function(o,i){return '<div class="review-option '+(i===a.selected?'user-wrong ':'')+(i===Number(q.answer)?'correct':'')+'">'+String.fromCharCode(65+i)+') '+o+(i===a.selected?' · Senin cevabın':'')+(i===Number(q.answer)?' · Doğru cevap':'')+'</div>'}).join('');if(id('reviewSolution'))id('reviewSolution').textContent=q.solution||'';if(id('prevReview'))id('prevReview').disabled=reviewIndex===0;if(id('nextReview'))id('nextReview').textContent=reviewIndex===reviewItems.length-1?'Bitti':'Sonraki'}
function openNotes(name){noteSubject=name;noteIndex=0;renderSmartNotes();showPage('smartnotes')}
function renderSmartNotes(){var list=notes()[noteSubject]||[],n=list[noteIndex];if(id('smartNotesSubjectTitle'))id('smartNotesSubjectTitle').textContent=noteSubject;if(id('smartNotesCounter'))id('smartNotesCounter').textContent=list.length?(noteIndex+1)+' / '+list.length:'0 / 0';if(id('smartNoteSubjectTabs'))id('smartNoteSubjectTabs').innerHTML=SUBJECTS.map(function(s){return '<button data-note-subject="'+s.name+'" class="'+(s.name===noteSubject?'selected':'')+'" style="--c:'+s.color+'">'+s.short+'</button>'}).join('');all('[data-note-subject]').forEach(function(b){b.onclick=function(){noteSubject=b.getAttribute('data-note-subject');noteIndex=0;renderSmartNotes()}});if(!n){if(id('smartNoteTitle'))id('smartNoteTitle').textContent='Bu ders için notlar hazırlanıyor';if(id('smartNoteConcept'))id('smartNoteConcept').textContent='';if(id('smartNoteAttention'))id('smartNoteAttention').textContent='';if(id('smartNoteExample'))id('smartNoteExample').textContent='';return}if(id('smartNoteTopic'))id('smartNoteTopic').textContent=n.topic||'Konu';if(id('smartNoteTitle'))id('smartNoteTitle').textContent=n.title||'';if(id('smartNoteConcept'))id('smartNoteConcept').textContent=n.concept||'';if(id('smartNoteAttention'))id('smartNoteAttention').textContent=n.attention||'';if(id('smartNoteExample'))id('smartNoteExample').textContent=n.example||'';if(id('prevSmartNote'))id('prevSmartNote').disabled=noteIndex===0;if(id('nextSmartNote'))id('nextSmartNote').disabled=noteIndex===list.length-1}
function zeusReply(text){var weak=SUBJECTS.map(function(s){return {name:s.name,a:accuracy(s.name)}}).sort(function(a,b){return a.a-b.a})[0];var msg='Öncelikli dersin '+weak.name+'. Önce Akıllı Notlar, sonra 10 hedef soru öneriyorum.';if(String(text||'').toLocaleLowerCase('tr-TR').indexOf('plan')>=0)msg='Bugün önce '+weak.name+' dersinden 10 soru, ardından güçlü olduğun bir dersten 10 soru çöz.';var p=document.createElement('p');p.innerHTML='<b>Zeus:</b> '+msg;var box=id('zeusMessages');if(box){box.appendChild(p);box.scrollTop=9999}}
function updateCountdown(){var now=new Date(),target=new Date(2027,5,13,9,30),d=target-now,days=Math.max(0,Math.floor(d/86400000)),h=Math.max(0,Math.floor((d%86400000)/3600000)),m=Math.max(0,Math.floor((d%3600000)/60000)),s=Math.max(0,Math.floor((d%60000)/1000));if(id('daysLeft'))id('daysLeft').textContent=days;if(id('clockLeft'))id('clockLeft').textContent=h+' saat · '+m+' dakika · '+s+' saniye'}
function openWeeklyExam(){if(window.LgsArenaWeeklyExam&&typeof window.LgsArenaWeeklyExam.open==='function'){window.LgsArenaWeeklyExam.open();return}if(window.LgsArenaWeeklyExam&&typeof window.LgsArenaWeeklyExam.start==='function'){window.LgsArenaWeeklyExam.start();return}toast('90 soruluk haftalık deneme modülü hazırlanıyor. Sayfayı bir kez yenileyip tekrar deneyin.')}
function wire(){
 all('[data-nav]').forEach(function(b){b.addEventListener('click',function(){showPage(b.getAttribute('data-nav'))})});
 if(id('quickStart'))id('quickStart').onclick=startQuick;if(id('startMock'))id('startMock').onclick=openWeeklyExam;if(id('hintBtn'))id('hintBtn').onclick=function(){help('hint')};if(id('solutionBtn'))id('solutionBtn').onclick=function(){help('solution')};if(id('askZeusBtn'))id('askZeusBtn').onclick=function(){help('zeus')};if(id('nextBtn'))id('nextBtn').onclick=nextQuestion;
 if(id('quitQuiz'))id('quitQuiz').onclick=function(){stopTimer();session=null;if(id('solveLauncher'))id('solveLauncher').classList.remove('hidden');if(id('quizView'))id('quizView').classList.add('hidden');showPage('arena')};
 if(id('resultHome'))id('resultHome').onclick=function(){session=null;if(id('solveLauncher'))id('solveLauncher').classList.remove('hidden');if(id('quizView'))id('quizView').classList.add('hidden');showPage('arena')};if(id('reviewWrong'))id('reviewWrong').onclick=openReview;if(id('closeReview'))id('closeReview').onclick=function(){showPage('result')};if(id('prevReview'))id('prevReview').onclick=function(){if(reviewIndex>0){reviewIndex--;renderReview()}};if(id('nextReview'))id('nextReview').onclick=function(){if(reviewIndex<reviewItems.length-1){reviewIndex++;renderReview()}else showPage('result')};
 if(id('smartNotesBack'))id('smartNotesBack').onclick=function(){showPage('subjects')};if(id('prevSmartNote'))id('prevSmartNote').onclick=function(){if(noteIndex>0){noteIndex--;renderSmartNotes()}};if(id('nextSmartNote'))id('nextSmartNote').onclick=function(){var l=notes()[noteSubject]||[];if(noteIndex<l.length-1){noteIndex++;renderSmartNotes()}};if(id('smartNotePractice'))id('smartNotePractice').onclick=function(){startPractice(noteSubject)};
 if(id('togglePlan'))id('togglePlan').onclick=function(){state.isPremium=!state.isPremium;persist();toast(state.isPremium?'Reklamsız sonuç akışı açık.':'Ücretsiz reklam akışı açık.')};
 if(id('zeusSend'))id('zeusSend').onclick=function(){var i=id('zeusInput'),v=i?i.value.trim():'';if(!v)return;var p=document.createElement('p');p.textContent='Sen: '+v;id('zeusMessages').appendChild(p);i.value='';zeusReply(v)};if(id('zeusInput'))id('zeusInput').onkeydown=function(e){if(e.key==='Enter'&&id('zeusSend'))id('zeusSend').click()};all('[data-zeus-action]').forEach(function(b){b.onclick=function(){var a=b.getAttribute('data-zeus-action');if(a==='test')startQuick();else if(a==='plan'||a==='weak')zeusReply(a);else if(id('zeusInput'))id('zeusInput').focus()}});
}
function init(){try{normalizeDay();setupProvince();renderLaunchers();renderSubjects();wire();renderAll();updateCountdown();setInterval(updateCountdown,1000);showPage('arena');document.documentElement.setAttribute('data-core-ready','23');window.LgsArenaCore={showPage:showPage,startPractice:startPractice,startQuick:startQuick,state:function(){return state},refresh:renderAll};console.info('LGS Arena core V2.3 ready')}catch(e){fatal(e&&e.message?e.message:String(e))}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();