(function(){
'use strict';
var PROFILE_KEY='lgsArenaStudentProfileV20';
var PARENT_KEY='lgsArenaParentPortalV2';
var busy=false;
function byId(x){return document.getElementById(x)}
function read(key){try{return JSON.parse(localStorage.getItem(key)||'{}')||{}}catch(e){return {}}}
function saveName(name){var old=read(PROFILE_KEY);var p={name:name,createdAt:old.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),storage:'device-demo'};try{localStorage.setItem(PROFILE_KEY,JSON.stringify(p));var parent=read(PARENT_KEY);parent.studentName=name;localStorage.setItem(PARENT_KEY,JSON.stringify(parent))}catch(e){}return p}
function addChip(name){var chip=byId('studentNameChip');if(!chip){chip=document.createElement('div');chip.id='studentNameChip';chip.className='student-name-chip';var brand=document.querySelector('.brand');if(brand)brand.appendChild(chip)}if(chip)chip.textContent=name}
function enter(name){var overlay=byId('entryV26Overlay');if(overlay)overlay.remove();var cover=byId('cover'),shell=byId('shell');if(cover){cover.classList.remove('active');cover.classList.add('hidden')}if(shell)shell.classList.remove('hidden');addChip(name);try{window.dispatchEvent(new CustomEvent('lgsarena:student-enter',{detail:{name:name}}))}catch(e){}busy=false}
function makeGate(){var existing=byId('entryV26Overlay');if(existing){existing.style.display='grid';return}var p=read(PROFILE_KEY),has=!!String(p.name||'').trim();var el=document.createElement('div');el.id='entryV26Overlay';el.style.cssText='position:fixed;inset:0;z-index:2147483647;display:grid;place-items:center;padding:20px;background:rgba(1,7,16,.94);font-family:Arial,sans-serif;color:#fff';el.innerHTML='<div style="width:min(92vw,390px);border:1px solid rgba(242,189,88,.45);border-radius:22px;padding:22px;background:linear-gradient(145deg,#0b223d,#061426);box-shadow:0 24px 60px #000a;text-align:center"><div style="font-size:34px">⚡</div><div style="font-size:11px;letter-spacing:2px;color:#f2bd58;font-weight:900;margin-top:5px">LGS ARENA</div><h2 style="font:800 24px Georgia,serif;margin:10px 0">'+(has?'Hoş geldin, '+String(p.name).replace(/[&<>\"']/g,''):'Öğrenci Girişi')+'</h2><p style="font-size:12px;line-height:1.45;color:#b7cadc">'+(has?'Bu cihazdaki çalışma geçmişinle devam edebilirsin.':'Arena ilerlemesini bu öğrenci adıyla kaydedecek.')+'</p>'+(has?'':'<input id="entryV26Name" maxlength="24" autocomplete="nickname" placeholder="Öğrenci adı" style="width:100%;margin:8px 0 12px;padding:13px 14px;border-radius:12px;border:1px solid #397dff88;background:#031020;color:#fff;font-size:16px;outline:none">')+'<button id="entryV26Continue" style="width:100%;padding:13px;border:0;border-radius:12px;background:linear-gradient(90deg,#1768ff,#34bff2);color:#fff;font-weight:900;font-size:13px">'+(has?'ARENAYA DEVAM ET':'PROFİLİ OLUŞTUR VE DEVAM ET')+'</button><button id="entryV26Cancel" style="width:100%;margin-top:9px;padding:10px;border:1px solid #ffffff22;border-radius:11px;background:transparent;color:#a9bed3;font-weight:700">GERİ DÖN</button><small style="display:block;margin-top:13px;color:#718ba5;font-size:9px;line-height:1.4">Demo sürümünde ilerleme bu cihazda saklanır.</small></div>';document.body.appendChild(el);var cont=byId('entryV26Continue');if(cont)cont.onclick=function(){var current=read(PROFILE_KEY),name=String(current.name||'').trim();if(!name){var input=byId('entryV26Name');name=String(input&&input.value||'').trim();if(name.length<2){if(input)input.focus();return}saveName(name)}enter(name)};var cancel=byId('entryV26Cancel');if(cancel)cancel.onclick=function(){el.remove();busy=false};if(!has){setTimeout(function(){var i=byId('entryV26Name');if(i)i.focus()},50)}}
function openEntry(){if(busy)return;busy=true;makeGate()}
function targetIsEntry(e){var t=e&&e.target;if(t&&t.closest&&t.closest('#skipCover'))return true;var touch=e&&e.changedTouches&&e.changedTouches[0];if(touch){var hit=document.elementFromPoint(touch.clientX,touch.clientY);if(hit&&hit.closest&&hit.closest('#skipCover'))return true}return false}
function intercept(e){if(!targetIsEntry(e))return;if(e.cancelable)e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();openEntry()}
function arm(){var b=byId('skipCover');if(b){b.style.zIndex='2147483000';b.style.pointerEvents='auto';b.style.touchAction='manipulation';b.setAttribute('data-entry-v26','1')}document.addEventListener('pointerup',intercept,true);document.addEventListener('touchend',intercept,{capture:true,passive:false});document.addEventListener('click',intercept,true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',arm,{once:true});else arm();
window.LgsArenaEntryV26={open:openEntry,enter:enter};
})();