'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=name=>fs.readFileSync(path.join(root,name),'utf8');
const index=read('index.html'),profile=read('profile-parent-v41.js'),preference=read('preference-v60.js'),pwa=read('pwa.js'),config=read('config.js'),sw=read('service-worker.js'),css=read('access-v63.css'),manifest=JSON.parse(read('manifest.webmanifest'));
let source=read('app.js');
const closeMarker='init();\n})();';
assert(source.includes(closeMarker),'app test hook marker missing');
source=source.replace(closeMarker,`globalThis.__arenaTest={today:()=>today(),setState:value=>{state={...defaults,...value}},getState:()=>state,freeQuestionTake,showRewardedAd,nextIstanbulEight,hasPremiumAccess,isFreeLocked};\n})();`);
function classList(initial=['hidden']){const values=new Set(initial);return {add:v=>values.add(v),remove:v=>values.delete(v),contains:v=>values.has(v),toggle:(v,on)=>on?values.add(v):values.delete(v)}}
function element(){return {textContent:'',classList:classList(),attrs:{},setAttribute(k,v){this.attrs[k]=v}}}
const elements={quotaOverlay:element(),quotaTitle:element(),quotaText:element(),adOverlay:element(),adCount:element(),adTitle:element(),adMessage:element(),adQuota:element(),toast:element()};
let intervalCallback=null,intervalCleared=false;const stored={};
const context={console,localStorage:{getItem:k=>stored[k]||null,setItem:(k,v)=>{stored[k]=v}},document:{getElementById:id=>elements[id]||null,querySelector:()=>null,querySelectorAll:()=>[],body:{classList:classList([])}},window:{dispatchEvent:()=>{},addEventListener:()=>{},__toast:null},CustomEvent:function(type,init){this.type=type;this.detail=init?.detail},setTimeout:()=>1,clearTimeout:()=>{},setInterval:fn=>{intervalCallback=fn;return 7},clearInterval:()=>{intervalCleared=true},URLSearchParams,Date,Intl,Math,JSON};context.globalThis=context;vm.createContext(context);vm.runInContext(source,context,{filename:'app.js'});const api=context.__arenaTest,day=api.today();
api.setState({daily:{date:day,count:40},noteRewards:{date:day,subjects:[]},rewardDaily:{date:day,count:0},isPremium:false,timeoutEvents:[],examHistory:[]});assert.strictEqual(api.freeQuestionTake(),10,'free block should be 10');
api.setState({daily:{date:day,count:46},noteRewards:{date:day,subjects:[]},rewardDaily:{date:day,count:0},isPremium:false,timeoutEvents:[],examHistory:[]});assert.strictEqual(api.freeQuestionTake(),4,'free questions must stop at 50');
api.setState({daily:{date:day,count:50},noteRewards:{date:day,subjects:[]},rewardDaily:{date:day,count:0},isPremium:false,timeoutEvents:[],examHistory:[]});assert.strictEqual(api.freeQuestionTake(),0,'free quota should lock at 50');assert(!elements.quotaOverlay.classList.contains('hidden'),'question quota gate should be visible');
api.setState({daily:{date:day,count:50},noteRewards:{date:day,subjects:[]},rewardDaily:{date:day,count:6},isPremium:false,freePremiumUntil:new Date(Date.now()+86400000).toISOString(),timeoutEvents:[],examHistory:[]});assert.strictEqual(api.freeQuestionTake(),10,'referral Premium should bypass quotas');
let fifthComplete=false;api.setState({daily:{date:day,count:0},noteRewards:{date:day,subjects:[]},rewardDaily:{date:day,count:4},isPremium:false,timeoutEvents:[],examHistory:[]});assert(api.showRewardedAd('Ders özetine devam',()=>{fifthComplete=true}));for(let i=0;i<7;i++)intervalCallback();assert(!fifthComplete,'reward must remain locked before full ad');intervalCallback();assert(fifthComplete,'fifth completed ad should advance');assert.strictEqual(api.getState().rewardDaily.count,5);
let sixthComplete=false;intervalCleared=false;elements.quotaOverlay.classList.add('hidden');assert(api.showRewardedAd('Ders özetine devam',()=>{sixthComplete=true}));for(let i=0;i<8;i++)intervalCallback();assert(!sixthComplete,'sixth ad must lock instead of advancing');assert.strictEqual(api.getState().rewardDaily.count,6);assert(api.isFreeLocked(),'sixth ad must set free lock');assert(!elements.quotaOverlay.classList.contains('hidden'),'daily ad lock warning must be visible');
const unlock=new Date(api.getState().freeLockUntil),localHour=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Istanbul',hour:'2-digit',hour12:false}).format(unlock);assert.strictEqual(localHour,'08','unlock must be 08:00 Istanbul');assert(unlock>Date.now(),'unlock must be in the future');
const profileStore={lgsArenaPwaV02:'{}'},profileContext={console,localStorage:{getItem:k=>profileStore[k]||null,setItem:(k,v)=>{profileStore[k]=v}},document:{readyState:'loading',addEventListener:()=>{},querySelector:()=>null,getElementById:()=>null},window:{dispatchEvent:()=>{},addEventListener:()=>{}},CustomEvent:function(type,init){this.type=type;this.detail=init?.detail},navigator:{userAgent:'Android 16 Chrome',share:null,clipboard:{writeText:async()=>{}}},screen:{width:412,height:915},innerWidth:412,innerHeight:915,location:{href:'https://example.test/'},URL,Date,Intl,Math,JSON,setTimeout:()=>1,clearTimeout:()=>{}};profileContext.globalThis=profileContext;vm.createContext(profileContext);vm.runInContext(profile,profileContext,{filename:'profile-parent-v41.js'});const parent=profileContext.window.LgsArenaParent;assert(parent,'parent API missing');assert(parent.applyReferralReward('friend-1').ok);assert(parent.applyReferralReward('friend-2').rewardDays===2);assert(parent.applyReferralReward('friend-3').rewardDays===3);assert(!parent.applyReferralReward('friend-3').ok,'duplicate referral must not count');const rewardState=JSON.parse(profileStore.lgsArenaPwaV02);assert.strictEqual(rewardState.referralFriendIds.length,3);assert(Date.parse(rewardState.freePremiumUntil)>Date.now()+5.9*86400000,'referrals should award 1+2+3 days');
const ids=[...index.matchAll(/\sid="([^"]+)"/g)].map(x=>x[1]),duplicates=ids.filter((id,i)=>ids.indexOf(id)!==i);assert.deepStrictEqual(duplicates,[],'HTML ids must be unique');
assert(index.includes('PWA-ID 20260824-09')&&manifest.start_url.includes('20260824-09'),'visible and manifest build IDs must align');assert(index.includes('data-nav="arena" aria-label="Durum"')&&index.includes('<span>Durum</span>'),'Durum tab missing');assert(index.includes('data-nav="solve" aria-label="Arena"')&&index.includes('m13.5 2-8 11h6l-1 9 8-12h-6z'),'Arena lightning tab missing');assert(index.includes('id="studentProfileChip"')&&index.indexOf('id="studentProfileChip"')<index.indexOf('</header>'),'profile must be in header');assert(!index.includes('<div><span>DENEME</span><h2>LGS 2027 Arena'),'DENEME kicker must be removed from 90-question card');assert.strictEqual((index.match(/data-written-scenario=/g)||[]).length,4,'four written scenarios required');
assert(index.includes('id="contentGate"')&&index.includes('id="adQuota"'),'lesson summary choice/ad quota UI missing');assert(index.includes('id="preferenceFormalWarning"')&&index.includes('yerleşme garantisi niteliği taşımaz'),'formal preference warning missing');assert(preference.includes("if(!text)return null")&&preference.includes("showFormalWarning(true)"),'score-only/formal-warning logic missing');assert(profile.includes("cover?.classList.add('hidden')")&&profile.includes("openMembership()"),'cover parent redirect fix missing');assert(profile.includes('Veli Takip için 6 haneli giriş kodu')&&profile.includes('Arkadaşına Tavsiye Et'),'profile pairing/referral UI missing');
assert(config.includes("legalNotice:LEGAL")&&config.includes("LEGAL='Türkiye Yüzyılı Maarif Modeli dikkate alınmıştır.'"),'simplified legal copy missing');assert(!config.includes('MEB onayı')&&!pwa.includes('MEB onayı'),'old cover disclaimer must not be displayed');assert(pwa.includes("RELEASE='6.3.0',BUILD_ID='20260824-09'")&&pwa.includes("access-v63.css"),'PWA build/style alignment missing');assert(sw.includes('lgs-2027-arena-pwa-v6.3.0-build-20260824-09')&&sw.includes("'./access-v63.css'"),'service worker cache alignment missing');assert(css.includes('.header-profile-chip.student-chip')&&css.includes('.content-gate'),'access UI CSS missing');
const combined=source+profile+preference;assert(!/localStorage\.(clear|removeItem)/.test(combined),'existing localStorage must not be cleared');
const shellMatch=sw.match(/const APP_SHELL=\[(.*?)\];/s);assert(shellMatch,'service worker shell list missing');const shellFiles=[...shellMatch[1].matchAll(/'\.\/([^']+)'/g)].map(x=>x[1].split('?')[0]).filter(x=>x&&x!=='');for(const file of shellFiles)assert(fs.existsSync(path.join(root,file)),`cached file missing: ${file}`);
for(const icon of manifest.icons){const buffer=fs.readFileSync(path.join(root,icon.src));assert(buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),`invalid PNG: ${icon.src}`);const width=buffer.readUInt32BE(16),height=buffer.readUInt32BE(20),expected=Number(icon.sizes.split('x')[0]);assert.strictEqual(width,expected);assert.strictEqual(height,expected)}
const hero=fs.readFileSync(path.join(root,'assets/zeus-hero-20260823-02.webp'));assert.strictEqual(hero.subarray(0,4).toString(),'RIFF');assert.strictEqual(hero.subarray(8,12).toString(),'WEBP');
console.log(JSON.stringify({ok:true,version:'6.3.0',buildId:'20260824-09',freeDailyQuestions:50,rewardedAdsPerDay:6,unlockHour:'08:00 Europe/Istanbul',referralRewards:[1,2,3],localStoragePreserved:true,appShellFiles:shellFiles.length}));
