plugins {
    id 'com.android.application'
}

android {
    namespace 'com.zorbirey.lgs2027arena'
    compileSdk 35

    defaultConfig {
        applicationId 'com.zorbirey.lgs2027arena'
        minSdk 23
        targetSdk 35
        versionCode 11
        versionName '0.11'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
